local PuzzleLibrary = {
	Standard = {
		{
			title = "Bakery Bash",
			subtitle = "Warm trays, sweet counters, quick finds.",
			gridSize = 7,
			words = { "BAGEL", "BAKER", "BREAD", "COOKIE", "CRUST", "DONUT", "FLOUR", "GLAZE", "ICING", "MUFFIN", "OVEN", "ROLL" },
		},
		{
			title = "Aquarium Run",
			subtitle = "Glass tunnels and bright reef life.",
			gridSize = 8,
			words = { "BUBBLE", "CORAL", "CURRENT", "DOLPHIN", "EEL", "JELLY", "KELP", "OTTER", "REEF", "SHELL", "TURTLE", "WHALE" },
		},
		{
			title = "Space Port",
			subtitle = "Lift off lanes and orbital traffic.",
			gridSize = 8,
			words = { "ASTRO", "COMET", "GALAXY", "LAUNCH", "METEOR", "NEBULA", "ORBIT", "PLANET", "ROCKET", "SATURN", "STAR", "THRUST" },
		},
		{
			title = "Jungle Trek",
			subtitle = "Dense leaves, drums, and hidden trails.",
			gridSize = 8,
			words = { "CANOPY", "DRUM", "JAGUAR", "JUNGLE", "MONKEY", "PARROT", "RIVER", "TEMPLE", "TIGER", "TOTEM", "TRAIL", "VINE" },
		},
		{
			title = "Toy Box",
			subtitle = "Bright shelves and classic playroom finds.",
			gridSize = 7,
			words = { "BLOCK", "CRAYON", "DOLL", "GAME", "MARBLE", "PAINT", "PUZZLE", "ROBOT", "SCOOTER", "TOYBOX", "TRAIN", "YOYO" },
		},
		{
			title = "Movie Night",
			subtitle = "Lights down, projector on.",
			gridSize = 8,
			words = { "ACTOR", "CAMERA", "CINEMA", "COMEDY", "CREDITS", "POPCORN", "POSTER", "REEL", "SCENE", "SCREEN", "TICKET", "USHER" },
		},
		{
			title = "Road Trip",
			subtitle = "Long roads, loud songs, snack stops.",
			gridSize = 8,
			words = { "ATLAS", "BRAKE", "CABIN", "CAMP", "FREEWAY", "GAS", "HOTEL", "MILE", "ROUTE", "SIGN", "TRUCK", "WAGON" },
		},
		{
			title = "Science Lab",
			subtitle = "Bubbling glass and tidy notebooks.",
			gridSize = 8,
			words = { "ATOM", "BEAKER", "BURNER", "FORMULA", "LASER", "MAGNET", "MIXER", "NOTES", "PIPETTE", "SENSOR", "THEORY", "TUBE" },
		},
		{
			title = "Farm Market",
			subtitle = "Fresh rows and early morning crates.",
			gridSize = 7,
			words = { "APPLE", "BARN", "BERRY", "CRATE", "FIELD", "GOAT", "HARVEST", "HAY", "MELON", "PEACH", "TRACTOR", "WHEAT" },
		},
		{
			title = "Mountain Camp",
			subtitle = "Cold air and a glowing fire ring.",
			gridSize = 8,
			words = { "BOOTS", "CAMP", "CLIFF", "ECHO", "FIRE", "HIKE", "LANTERN", "PEAK", "PINE", "RIDGE", "TENT", "TRAIL" },
		},
		{
			title = "Super Store",
			subtitle = "Aisles, carts, and checkout beeps.",
			gridSize = 8,
			words = { "AISLE", "BASKET", "CART", "CASHIER", "CEREAL", "COUPON", "FREEZER", "JUICE", "MARKET", "RECEIPT", "SHELF", "SNACK" },
		},
		{
			title = "Sports Arena",
			subtitle = "Crowds up, scoreboards lit.",
			gridSize = 8,
			words = { "ARENA", "COACH", "CROWD", "GOAL", "HELMET", "JERSEY", "MEDAL", "RALLY", "REFEREE", "SCORE", "TEAM", "WHISTLE" },
		},
		{
			title = "Build Site",
			subtitle = "Steel beams and concrete dust.",
			gridSize = 8,
			words = { "BEAM", "BOLT", "BRICK", "CRANE", "DRILL", "FRAME", "HAMMER", "LADDER", "LEVEL", "PLANK", "SAFETY", "TOOLBOX" },
		},
		{
			title = "Treasure Cove",
			subtitle = "Maps, lanterns, and buried shine.",
			gridSize = 8,
			words = { "ANCHOR", "CHEST", "CLUE", "COIN", "COVE", "GOLD", "ISLAND", "MAP", "PIRATE", "RUMOR", "SHOVEL", "VOYAGE" },
		},
		{
			title = "Dino Dig",
			subtitle = "Dusty bones and giant tracks.",
			gridSize = 8,
			words = { "BONE", "CLAW", "DIG", "DINOSAUR", "FOSSIL", "METEOR", "MUSEUM", "RAPTOR", "ROAR", "SCALES", "SKULL", "TAIL" },
		},
		{
			title = "Magic Show",
			subtitle = "Curtains, sparks, and quick hands.",
			gridSize = 8,
			words = { "CAPE", "CARD", "CRYSTAL", "DOVE", "MAGIC", "RABBIT", "SPELL", "STAGE", "STAR", "TRICK", "WAND", "WIZARD" },
		},
		{
			title = "Robot Room",
			subtitle = "Tiny gears and blinking panels.",
			gridSize = 8,
			words = { "BATTERY", "BOLT", "CIRCUIT", "CODE", "DRONE", "GEAR", "LASER", "METAL", "ROBOT", "SERVO", "SPARK", "SWITCH" },
		},
		{
			title = "Pet Parade",
			subtitle = "Happy paws and wagging tails.",
			gridSize = 7,
			words = { "BOWL", "COLLAR", "HAMSTER", "KITTEN", "LEASH", "PUPPY", "RABBIT", "SADDLE", "TREAT", "VET", "WHISKER", "YARN" },
		},
		{
			title = "Rainy City",
			subtitle = "Wet streets and bright windows.",
			gridSize = 8,
			words = { "AWNING", "BUS", "CROSSWALK", "DRIZZLE", "NEON", "PUDDLE", "RAINCOAT", "SIDEWALK", "STORM", "TAXI", "UMBRELLA", "WINDOW" },
		},
		{
			title = "Desert Trail",
			subtitle = "Sand paths and hot horizon lines.",
			gridSize = 8,
			words = { "CACTUS", "CAMEL", "CANYON", "DUNE", "HEAT", "LIZARD", "MESA", "MIRAGE", "OASIS", "SAND", "SCORPION", "SUNSET" },
		},
		{
			title = "Safari Run",
			subtitle = "Big sky and distant hoofbeats.",
			gridSize = 8,
			words = { "CHEETAH", "ELEPHANT", "GAZELLE", "JEEP", "LION", "RHINO", "SAVANNA", "TRACK", "VULTURE", "WATERHOLE", "ZEBRA", "ZOO" },
		},
		{
			title = "Ice Palace",
			subtitle = "Frozen halls and bright blue stone.",
			gridSize = 8,
			words = { "BLIZZARD", "CRYSTAL", "FROST", "GLACIER", "ICEBERG", "PALACE", "SHIVER", "SKATE", "SLED", "SNOW", "WINTER", "WOOL" },
		},
		{
			title = "Pirate Deck",
			subtitle = "Salt spray and rope swings.",
			gridSize = 8,
			words = { "BARREL", "CAPTAIN", "COMPASS", "CREW", "CUTLASS", "DECK", "FLAG", "HARBOR", "HOOK", "PARROT", "PLANK", "RIGGING" },
		},
		{
			title = "Circus Tent",
			subtitle = "Bright lights and fast applause.",
			gridSize = 8,
			words = { "ACROBAT", "BALLOON", "CLOWN", "JUGGLE", "RING", "SPOTLIGHT", "STALL", "TENT", "TICKET", "TRAPEZE", "TRUMPET", "UNICYCLE" },
		},
		{
			title = "Castle Court",
			subtitle = "Stone walls and echoing steps.",
			gridSize = 8,
			words = { "ARMOR", "CASTLE", "COURT", "CROWN", "GUARD", "KNIGHT", "MOAT", "QUEEN", "SHIELD", "THRONE", "TOWER", "TRUMPET" },
		},
		{
			title = "Music Fest",
			subtitle = "Stage lights and heavy rhythm.",
			gridSize = 8,
			words = { "AMP", "BEAT", "CHORD", "DRUM", "ENCORE", "LYRIC", "MELODY", "NOTE", "RHYTHM", "SONG", "STAGE", "VINYL" },
		},
		{
			title = "Candy Shop",
			subtitle = "Glass jars and sugar rush lanes.",
			gridSize = 7,
			words = { "CANDY", "CARAMEL", "FUDGE", "GUMMY", "JELLY", "LICORICE", "LOLLIPOP", "MINT", "SPRINKLE", "TAFFY", "TOFFEE", "TRUFFLE" },
		},
		{
			title = "Art Studio",
			subtitle = "Paint drops and careful outlines.",
			gridSize = 8,
			words = { "BRUSH", "CANVAS", "CHARCOAL", "COLOR", "EASEL", "FRAME", "INK", "PALETTE", "PASTEL", "SKETCH", "STROKE", "WASH" },
		},
		{
			title = "Forest Trail",
			subtitle = "Mossy turns and hidden streams.",
			gridSize = 8,
			words = { "ACORN", "BIRCH", "BROOK", "DEER", "FERN", "FOX", "MOSS", "OWL", "PATH", "PINECONE", "STREAM", "WOODLAND" },
		},
		{
			title = "Beach Club",
			subtitle = "Salt air and bright umbrellas.",
			gridSize = 8,
			words = { "BOARDWALK", "BUOY", "COAST", "PALM", "SANDCASTLE", "SEASHELL", "SHORE", "SURF", "TIDE", "TOWEL", "WAVE", "WHARF" },
		},
		{
			title = "Airport Rush",
			subtitle = "Rolling bags and flashing gates.",
			gridSize = 8,
			words = { "ARRIVAL", "BAGGAGE", "BOARDING", "COCKPIT", "GATE", "JET", "PILOT", "RADAR", "RUNWAY", "SECURITY", "TERMINAL", "TOWER" },
		},
		{
			title = "Garden Party",
			subtitle = "Late sun and blooming paths.",
			gridSize = 8,
			words = { "ARBOR", "BLOOM", "BUTTERFLY", "FLOWER", "GARDEN", "HEDGE", "LAWN", "PETAL", "ROSE", "SEED", "STEM", "VASE" },
		},
		{
			title = "Volcano Base",
			subtitle = "Heat, sparks, and glowing stone.",
			gridSize = 8,
			words = { "ASH", "BASALT", "CRATER", "ERUPTION", "FLAME", "LAVA", "MAGMA", "RIDGE", "SMOKE", "VENT", "VOLCANO", "STONE" },
		},
		{
			title = "Deep Sea",
			subtitle = "Dark pressure and moving lights.",
			gridSize = 8,
			words = { "ABYSS", "ANGLER", "CURRENT", "DIVER", "JELLY", "LANTERN", "REEF", "SALT", "SQUID", "SUBMARINE", "TRENCH", "WHALE" },
		},
		{
			title = "Comic Corner",
			subtitle = "Panels, ink, and caped pages.",
			gridSize = 8,
			words = { "BUBBLE", "CAPE", "COMIC", "HERO", "INK", "ISSUE", "MASK", "PANEL", "PUNCH", "SIDEKICK", "SPLASH", "VILLAIN" },
		},
		{
			title = "Pixel Arcade",
			subtitle = "Blinking cabinets and score chases.",
			gridSize = 8,
			words = { "ARCADE", "BONUS", "COIN", "COMBO", "HIGHSCORE", "JOYSTICK", "LASER", "LEVEL", "PIXEL", "SCORE", "TOKEN", "WARP" },
		},
		{
			title = "Secret Agent",
			subtitle = "Shadows, codes, and clean exits.",
			gridSize = 8,
			words = { "AGENT", "ALIAS", "BRIEF", "CLUE", "CODE", "GADGET", "LASER", "MISSION", "SHADOW", "STEALTH", "TARGET", "VAULT" },
		},
		{
			title = "Myth Hall",
			subtitle = "Ancient stories carved in stone.",
			gridSize = 8,
			words = { "ATLAS", "CENTAUR", "DRAGON", "GIANT", "HYDRA", "LEGEND", "MEDUSA", "MYTH", "ORACLE", "PHOENIX", "TITAN", "TEMPLE" },
		},
	},
	Mega = {
		{
			title = "Skyport Sprawl",
			subtitle = "A vast airborne city hunt.",
			gridSize = 20,
			words = { "AIRSHIP", "ARRIVAL", "BAZAAR", "CARGO", "CATWALK", "COMPASS", "CONTROL", "DOCK", "ENGINE", "GATEWAY", "GLIDER", "HANGAR", "LANDING", "MARKET", "PROPELLER", "RUNWAY", "SHUTTLE", "SKYBRIDGE", "SKYPORT", "STATION", "TERMINAL", "TOWER", "TRAVELER", "WINCH" },
		},
		{
			title = "Monster Museum",
			subtitle = "Huge halls full of strange exhibits.",
			gridSize = 20,
			words = { "ARCHIVE", "ARTIFACT", "BEAST", "CARVING", "CHAMBER", "CURATOR", "DISPLAY", "EXHIBIT", "FANG", "FOSSIL", "GALLEY", "GIANT", "GOBLIN", "GRIFFIN", "LEGEND", "MANUSCRIPT", "MINOTAUR", "MONSTER", "RELIC", "SKELETON", "SPHINX", "STATUE", "VAULT", "WING" },
		},
		{
			title = "Mythic Kingdom",
			subtitle = "A giant royal board with old magic.",
			gridSize = 20,
			words = { "ARMORY", "BANNER", "BASTION", "CASTLE", "CATAPULT", "CHAMPION", "COURTYARD", "CROWN", "DRAGON", "ENCHANT", "FORTRESS", "GATEHOUSE", "KINGDOM", "KNIGHT", "LANTERN", "LEGEND", "MOAT", "ORACLE", "PALADIN", "QUEEN", "SCEPTER", "THRONE", "TOWER", "WARDEN" },
		},
		{
			title = "Cyber City",
			subtitle = "Neon routes and layered systems.",
			gridSize = 20,
			words = { "ALGORITHM", "ANDROID", "ARCADE", "BATTERY", "CIRCUIT", "CONSOLE", "CYBER", "DATA", "DISPLAY", "DRONE", "ENGINE", "FIREWALL", "GLITCH", "HOLOGRAM", "INTERFACE", "NETWORK", "NEURAL", "PIXEL", "ROUTER", "SERVER", "SIGNAL", "SYNTH", "TERMINAL", "VECTOR" },
		},
		{
			title = "Ocean Trench",
			subtitle = "Cold depths and giant creatures.",
			gridSize = 20,
			words = { "ABYSS", "ANCHOR", "BIOGLOW", "BUBBLE", "CURRENT", "DIVER", "EEL", "GILL", "HADAL", "JELLY", "KELP", "KRILL", "LANTERN", "MARINER", "PRESSURE", "REEF", "SALTWATER", "SEAFLOOR", "SQUID", "SUBMARINE", "TIDE", "TRENCH", "VENT", "WHALE" },
		},
		{
			title = "Jungle Expedition",
			subtitle = "Deep canopy, ruins, and river turns.",
			gridSize = 20,
			words = { "ARCHAEOLOGY", "BACKPACK", "CANOPY", "COMPASS", "DRUM", "EXPEDITION", "FERN", "JAGUAR", "JOURNAL", "JUNGLE", "LANTERN", "MACAW", "MONKEY", "MOSS", "PARROT", "RUINS", "RIVER", "SATCHEL", "SCOUT", "TEMPLE", "TOTEM", "TRAIL", "VINE", "WATERFALL" },
		},
		{
			title = "Snow Fortress",
			subtitle = "A giant frozen stronghold board.",
			gridSize = 20,
			words = { "AVALANCHE", "BLIZZARD", "CITADEL", "CRYSTAL", "DRIFT", "FROST", "GLACIER", "ICEBERG", "LANTERN", "PALACE", "RAMPART", "SHIVER", "SLED", "SNOWFALL", "SNOWMAN", "SPARKLE", "SPIRE", "SUMMIT", "TUNDRA", "WATCHTOWER", "WHITEOUT", "WINTER", "WOOL", "YETI" },
		},
		{
			title = "Space Colony",
			subtitle = "A huge off-world station hunt.",
			gridSize = 20,
			words = { "AIRLOCK", "ANTENNA", "ASTEROID", "CAPSULE", "COLONY", "COMMAND", "COSMIC", "DOCKING", "GALAXY", "GRAVITY", "HABITAT", "LAUNCH", "LUNAR", "MISSION", "NEBULA", "ORBIT", "PANEL", "PLANET", "RADIANT", "ROVER", "SATELLITE", "SHUTTLE", "SOLAR", "THRUSTER" },
		},
		{
			title = "Treasure Fleet",
			subtitle = "Ships, maps, and stormy water.",
			gridSize = 20,
			words = { "ADMIRAL", "ANCHOR", "BARREL", "CAPTAIN", "CHART", "CHEST", "COMPASS", "CORSAIR", "CUTLASS", "DECK", "FLEET", "GALLEON", "HARBOR", "ISLAND", "LANTERN", "PLANK", "PRIVATEER", "RIGGING", "ROPE", "SAIL", "SHIPYARD", "TIDE", "TREASURE", "VOYAGE" },
		},
		{
			title = "Ancient Wonders",
			subtitle = "Massive ruins and forgotten halls.",
			gridSize = 20,
			words = { "ARCHWAY", "CARVING", "CHAMBER", "COLUMN", "DESERT", "EMPIRE", "FRESCO", "GLYPH", "GRANITE", "HIEROGLYPH", "LABYRINTH", "MARBLE", "MONUMENT", "OBELISK", "ORACLE", "PYRAMID", "RELIC", "RUINS", "SANDSTONE", "SCROLL", "TEMPLE", "TRIBUTE", "VAULT", "WONDER" },
		},
		{
			title = "Festival Plaza",
			subtitle = "A wide board full of lights and noise.",
			gridSize = 20,
			words = { "BALLOON", "BANNER", "BOOTH", "CARNIVAL", "CONFETTI", "DANCER", "DRUM", "FESTIVAL", "FIREWORK", "FLOAT", "FOODSTALL", "LANTERN", "MARKET", "MUSIC", "PARADE", "PLAZA", "PRIZE", "RIBBON", "SPARKLER", "SPOTLIGHT", "STAGE", "STREAMER", "TICKET", "VENDOR" },
		},
		{
			title = "Wild Safari",
			subtitle = "Open plains and fast-moving herds.",
			gridSize = 20,
			words = { "ACACIA", "ANTELOPE", "CAMPFIRE", "CHEETAH", "ELEPHANT", "EXPEDITION", "GAZELLE", "JEEP", "LANTERN", "LEOPARD", "LION", "OUTPOST", "RANGER", "RHINO", "RIVERBED", "SAVANNA", "SCOUT", "SUNRISE", "TRACKER", "VULTURE", "WATERHOLE", "WILDLIFE", "ZEBRA", "ZONE" },
		},
	},
	Daily = {
		{
			title = "World Expo",
			subtitle = "A huge daily map packed with global sights.",
			gridSize = 25,
			words = { "AIRPORT", "AMPHITHEATER", "ARCHWAY", "AVENUE", "BAZAAR", "BRIDGE", "CANAL", "CAPITAL", "CATHEDRAL", "COURTYARD", "DISTRICT", "EMBASSY", "EXHIBIT", "FESTIVAL", "FOUNTAIN", "GARDENS", "HARBOR", "LIBRARY", "MARKET", "METRO", "MONUMENT", "MUSEUM", "PAVILION", "PLAZA", "SKYLINE", "STATION", "STREET", "THEATER", "TOWER", "TRAVEL" },
		},
		{
			title = "Mythic Atlas",
			subtitle = "One giant daily hunt across old legends.",
			gridSize = 25,
			words = { "ALTAR", "AMULET", "ATLAS", "BEHEMOTH", "CENTAUR", "CHIMERA", "COLOSSUS", "CRYSTAL", "DRAGON", "ENCHANT", "FORTRESS", "GIANT", "GRIFFIN", "HYDRA", "KINGDOM", "LABYRINTH", "LEGEND", "MEDUSA", "MINOTAUR", "ORACLE", "PHOENIX", "SCEPTER", "SPHINX", "TEMPLE", "THUNDER", "TITAN", "TRIDENT", "VALKYRIE", "WARDEN", "ZEPHYR" },
		},
		{
			title = "Future Metropolis",
			subtitle = "A dense daily city board with neon layers.",
			gridSize = 25,
			words = { "ANDROID", "ANTENNA", "ARCADE", "AUTOPILOT", "BATTERY", "CIRCUIT", "CONSOLE", "CYBER", "DATASTREAM", "DISPLAY", "DRONE", "ELEVATOR", "FIREWALL", "GLITCH", "HOLOGRAM", "INTERFACE", "MEGACITY", "NETWORK", "NEURAL", "OVERPASS", "PIXEL", "ROUTER", "SERVER", "SKYBRIDGE", "SKYLINE", "STATION", "SYNTH", "TERMINAL", "TRANSIT", "VECTOR" },
		},
		{
			title = "Grand Safari",
			subtitle = "A wide daily route through wild country.",
			gridSize = 25,
			words = { "ACACIA", "ANTELOPE", "BACKTRACK", "CAMPGROUND", "CHEETAH", "ELEPHANT", "EXPLORER", "FIELDGUIDE", "GAZELLE", "HORIZON", "JEEP", "LANTERN", "LEOPARD", "LOOKOUT", "MIGRATION", "OUTPOST", "PANORAMA", "RANGER", "RHINO", "RIVERBED", "SAVANNA", "SUNRISE", "TRACKER", "VULTURE", "WATERHOLE", "WILDLIFE", "WINDSWEPT", "WOODLAND", "ZEBRA", "ZONE" },
		},
		{
			title = "Deep Blue Daily",
			subtitle = "A huge underwater board for the day.",
			gridSize = 25,
			words = { "ABYSS", "ANGLER", "BARNACLE", "BIOGLOW", "BUBBLE", "CURRENT", "DIVER", "EEL", "GILL", "JELLYFISH", "KELPFOREST", "KRILL", "LANTERN", "MARINER", "OCEAN", "OCTOPUS", "PRESSURE", "REEF", "SALTWATER", "SEAFLOOR", "SHIPWRECK", "SQUID", "SUBMARINE", "TIDEPOOL", "TRIDENT", "TRENCH", "TURTLE", "VENT", "WAVEFORM", "WHALE" },
		},
		{
			title = "Sky Kingdom",
			subtitle = "A giant high-altitude daily board.",
			gridSize = 25,
			words = { "AIRSHIP", "BALLOON", "BASTION", "BRIDGEWAY", "CASTLE", "CITADEL", "CLOUD", "COMPASS", "COURT", "DRAGON", "FLIGHTPATH", "GALLEON", "GATEHOUSE", "GLIDER", "KINGDOM", "LANTERN", "PALACE", "PARAPET", "PAVILION", "PROPELLER", "RAMPART", "RUNWAY", "SHUTTLE", "SKYBRIDGE", "SKYPORT", "SUMMIT", "TERMINAL", "THRONE", "TOWER", "WINDWAY" },
		},
		{
			title = "Ancient Empire",
			subtitle = "Massive stonework and hidden chambers.",
			gridSize = 25,
			words = { "AMPHORA", "ARCHWAY", "BASILICA", "CARVING", "CHAMBER", "COLUMN", "CORRIDOR", "DESERT", "EMPIRE", "FRESCO", "GLYPH", "GRANITE", "HALLWAY", "HIEROGLYPH", "MARBLE", "MONUMENT", "MOSAIC", "OBELISK", "PALACE", "PYRAMID", "RELIC", "RUINS", "SANCTUM", "SANDSTONE", "SCROLL", "STATUE", "TEMPLE", "THRONE", "TRIBUTE", "VAULT" },
		},
		{
			title = "Carnival Crown",
			subtitle = "A busy daily board full of lights and prizes.",
			gridSize = 25,
			words = { "ARCADE", "BALLOON", "BANNER", "BOOTH", "CARNIVAL", "CAROUSEL", "CONFETTI", "DANCER", "FERRIS", "FESTIVAL", "FIREWORK", "FLOAT", "FUNHOUSE", "LANTERN", "MIDWAY", "MUSIC", "PARADE", "PLAZA", "PRIZE", "RIBBON", "ROLLERCOASTER", "SPARKLER", "SPOTLIGHT", "STALL", "STAGE", "STREAMER", "TICKET", "TRUMPET", "VENDOR", "WONDER" },
		},
		{
			title = "Frozen Frontier",
			subtitle = "A giant daily ice field with sharp weather.",
			gridSize = 25,
			words = { "AURORA", "AVALANCHE", "BLIZZARD", "CRYSTAL", "DRIFT", "FROST", "GLACIER", "HAILSTONE", "ICEBERG", "LANTERN", "OUTPOST", "PALACE", "RIDGELINE", "SHIVER", "SLED", "SNOWDRIFT", "SNOWFIELD", "SNOWMAN", "SPARKLE", "SPIRE", "SUMMIT", "TUNDRA", "WATCHTOWER", "WHITEOUT", "WINDCHILL", "WINTER", "WOOL", "YETI", "ZONE", "ZEPHYR" },
		},
		{
			title = "Lost Jungle City",
			subtitle = "Ruins, rivers, and a huge green canopy.",
			gridSize = 25,
			words = { "ARCHAEOLOGY", "BACKPACK", "CANOPY", "CARVING", "CATARACT", "COMPASS", "DRUM", "EXPEDITION", "FERN", "JAGUAR", "JOURNAL", "JUNGLE", "LANTERN", "MONKEY", "MOSS", "OUTPOST", "PARROT", "PYRAMID", "RIVER", "RUINS", "SCOUT", "STATUE", "TEMPLE", "TOTEM", "TRAIL", "TRIBUTE", "VINE", "WATERFALL", "WOODLAND", "ZONE" },
		},
	},
}

return PuzzleLibrary
